name: Build for tvOS
on:
  pull_request:

jobs:
  build_tvOS:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: Swift build (tvOS)
        run: xcrun xcodebuild clean build -quiet -scheme DynamicUI -destination generic/platform=tvOS
