name: Run tests on macOS
on:
  pull_request:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  test_macOS:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Swift test
        run: swift test
